### ISSUE TITLE
Move Design Matrix Class to nltools

### ISSUE THREAD

**Issue by ljchang** [cosanlab/cosanlab_preproc#3]
@ejolly it might be better to move design matrix class under nltools and then just import it here for your new xMat interface.

**Comment by ejolly** [comment]
Sure that's an option. The reason I put it here for now is because nltools doesn't explicitly build any nipype nodes, which is how I have it implemented. But breaking it out into a flexible class that can handle parametric modulators, orthogonalization, etc is probably better.
